### ISSUE TITLE
Show the image and revised prompt

### ISSUE THREAD

**Issue by mcastillof** [Blizarre/microdalle#2]
Hello, I wonder if you can also add the revised prompt related to the image generated. Thanks

**Comment by Blizarre** [comment]
That is a great idea. It would really help with to get a good feedback loop.
The revised prompt is already included in the metadata json file that is saved with the file if you enable persistence.
I will add it to the UI

**Comment by Blizarre** [comment]
Done, I will close the issue as I have added the feature, you just need to pull the last  commit, have a great day!
